### ISSUE TITLE
Missing files for assembly

### ISSUE THREAD

**Issue by metabolonewbie** [chanana/hcapca#1]
Example and key files are missing for use, link is broken

**Comment by chanana** [comment]
Ah yeah sorry, the account where they were hosted was with my university and has since been deleted unfortunately. I'll try to reupload them elsewhere

**Comment by metabolonewbie** [comment]
Any update on files being available?

**Comment by chanana** [comment]
You can clone the repo and supply this file as an example data file. It should work
[example_feature_table.csv](https://github.com/chanana/hcapca/files/9172807/example_feature_table.csv)
